### ISSUE TITLE
r2dbc sample fails on startup

### ISSUE THREAD

**Issue by dsyer** [spring-projects-experimental/spring-fu#302]
The jafu r2dbc sample fails on startup:

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found; SQL statement:
DELETE FROM users [42102-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:453) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.readTableOrView(Parser.java:7628) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.readTableOrView(Parser.java:7599) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.readSimpleTableFilter(Parser.java:1350) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parseDelete(Parser.java:1377) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parsePrepared(Parser.java:914) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:843) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.parse(Parser.java:815) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.command.Parser.prepareCommand(Parser.java:738) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareLocal(Session.java:657) ~[h2-1.4.200.jar:1.4.200]
	at org.h2.engine.Session.prepareCommand(Session.java:595) ~[h2-1.4.200.jar:1.4.200]
	at io.r2dbc.h2.client.SessionClient.createCommand(SessionClient.java:154) ~[r2dbc-h2-0.8.3.RELEASE.jar:0.8.3.RELEASE]
	at io.r2dbc.h2.client.SessionClient.access$000(SessionClient.java:43) ~[r2dbc-h2-0.8.3.RELEASE.jar:0.8.3.RELEASE]
	at io.r2dbc.h2.client.SessionClient$1.next(SessionClient.java:117) ~[r2dbc-h2-0.8.3.RELEASE.jar:0.8.3.RELEASE]
	at io.r2dbc.h2.client.SessionClient$1.next(SessionClient.java:105) ~[r2dbc-h2-0.8.3.RELEASE.jar:0.8.3.RELEASE]
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:257) ~[reactor-core-3.4.0-M2.jar:na]
...
	at reactor.core.publisher.Mono.subscribe(Mono.java:3892) ~[reactor-core-3.4.0-M2.jar:na]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:173) ~[reactor-core-3.4.0-M2.jar:na]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56) ~[reactor-core-3.4.0-M2.jar:na]
	at reactor.core.publisher.Mono.subscribe(Mono.java:3892) ~[reactor-core-3.4.0-M2.jar:na]
	at reactor.core.publisher.Mono.block(Mono.java:1582) ~[reactor-core-3.4.0-M2.jar:na]
	at com.sample.UserRepository.init(UserRepository.java:48) ~[main/:na]
	at com.sample.Application.lambda$1(Application.java:13) ~[main/:na]

...
```

**Comment by sdeleuze** [comment]
This have been fixed.
