### ISSUE TITLE
Add support for Spring Data Elasticsearch

### ISSUE THREAD

**Issue by rgmz** [spring-projects-experimental/spring-fu#303]
Currently there is support for `cassandra`, `jdbc`, `mongo`, `r2dbc`, and `redis` -- it would be awesome to include [Spring Data Elasticsearch](https://spring.io/projects/spring-data-elasticsearch) as well.

*Alternatively*, can `@Enable...` annotations be used with the [`kofu` DSL](https://github.com/spring-projects-experimental/spring-fu/tree/master/kofu)?

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.data.elasticsearch.core.ReactiveElasticsearchOperations' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1717) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1273) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:884) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
        ... 98 common frames omitted
```

**Comment by sdeleuze** [comment]
No `@Enable...` can't with used with KoFu but we plan wider support via #273.
